# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [64]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import gmaps.datasets
import os
import json

# Import API key
from api_keys import g_key

gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [57]:
csv_path = "../WeatherPy/output_data/cities.csv"
csv_df = pd.read_csv(csv_path, index_col=0)
csv_df
csv_df['city'].nunique()
clean=csv_df.drop_duplicates(subset = ['city'],keep = 'first')
clean

,city,lat,max_temp,cloudiness,country,date,humidity,long,wind_speed
0,iqaluit,63.75,264.15,90,CA,1607208630,85,-68.51,7.20
1,jalu,29.03,291.00,19,LY,1607208862,29,21.55,7.68
2,yar-sale,66.83,261.30,57,RU,1607208862,96,70.83,3.83
3,coihaique,-45.58,299.15,0,CL,1607208862,31,-72.07,3.10
4,bengkulu,-3.80,297.70,95,ID,1607208863,80,102.27,2.16
5,albany,42.60,277.04,100,US,1607208758,60,-73.97,2.68
6,hasaki,35.73,278.15,75,JP,1607208863,100,140.83,3.10
7,diapaga,12.07,298.17,67,BF,1607208863,22,1.79,1.68
8,wagar,16.15,294.62,23,SD,1607208864,91,36.20,5.08
9,punta arenas,-53.15,289.15,0,CL,1607208478,59,-70.92,10.30
10,pevek,69.70,257.44,52,RU,1607208864,89,170.31,1.83
11,busselton,-33.65,287.04,42,AU,1607208864,74,115.33,0.45
12,ushuaia,-54.80,285.15,75,AR,1607208460,71,-68.30,6.70
13,chicama,-7.84,292.15,40,PE,1607208865,82,-79.15,5.70
14,hobart,-42.88,288.15,75,AU,1607208558,55,147.33,9.80
15,mataura,-46.19,288.71,89,NZ,1607208763,66,168.86,2.68
16,totness,5.88,299.23,100,SR,1607208865,86,-56.32,4.72
17,hamilton,39.18,277.59,20,US,1607208717,73,-84.53,0.45
18,gat,31.61,288.15,0,IL,1607208644,77,34.76,2.10
19,anaconda,46.13,277.15,1,US,1607208866,38,-112.94,2.02
20,kapaa,22.08,301.15,1,US,1607208866,65,-159.32,4.10
21,murashi,59.40,263.42,1,RU,1607208866,93,48.96,3.70
22,qaanaaq,77.48,248.46,29,GL,1607208866,68,-69.36,3.47
23,rikitea,-23.12,298.48,0,PF,1607208759,78,-134.97,6.20
24,san carlos del zulia,9.00,298.44,92,VE,1607208867,86,-71.91,2.25
25,mahibadhoo,3.78,301.45,100,MV,1607208867,74,72.97,5.72
26,bluff,-46.60,288.71,86,NZ,1607208766,66,168.33,2.68
27,kruisfontein,-34.00,291.48,14,ZA,1607208868,87,24.73,0.89
28,camacha,33.08,288.15,20,PT,1607208784,67,-16.33,6.70
29,sangar,63.92,245.65,100,RU,1607208868,88,127.47,2.65
30,kodiak,57.79,274.15,90,US,1607208868,69,-152.41,6.70
31,ayorou,14.73,298.90,14,NE,1607208868,18,0.92,2.45
32,tuktoyaktuk,69.45,251.15,5,CA,1607208779,83,-133.04,4.60
33,bredasdorp,-34.53,291.15,86,ZA,1607208869,82,20.04,4.10
34,cidreira,-30.18,291.41,100,BR,1607208760,75,-50.21,5.42
35,vaini,-21.20,300.15,75,TO,1607208784,78,-175.20,4.60
36,atuona,-9.80,299.06,27,PF,1607208762,74,-139.03,7.66
37,chokurdakh,70.63,238.57,26,RU,1607208870,81,147.92,3.01
38,mahebourg,-20.41,298.15,40,MU,1607208871,83,57.70,3.10
39,constitucion,-35.33,288.93,9,CL,1607208871,70,-72.42,3.91
40,butaritari,3.07,300.79,97,KI,1607208765,78,172.79,6.66
41,souillac,-20.52,298.15,40,MU,1607208871,83,57.52,3.10
42,victoria,22.29,289.26,0,HK,1607208503,71,114.16,0.45
43,olinda,-8.01,299.15,40,BR,1607208872,69,-34.86,4.10
44,srednekolymsk,67.45,241.34,90,RU,1607208872,87,153.68,0.48
45,port elizabeth,-33.92,292.15,90,ZA,1607208757,93,25.57,5.10
46,avarua,-21.21,301.15,93,CK,1607208872,78,-159.78,7.20
47,tautira,-17.73,304.15,40,PF,1607208883,62,-149.15,3.10
48,asilah,35.47,286.15,40,MA,1607208883,54,-6.03,4.60
49,port alfred,-33.59,293.31,80,ZA,1607208883,88,26.89,8.75
50,nanortalik,60.14,272.34,99,GL,1607208784,98,-45.24,1.04
51,castro,-24.79,289.16,100,BR,1607208883,96,-50.01,6.65
52,marrakesh,31.63,282.15,40,MA,1607208884,87,-8.01,1.50
53,juegang,32.32,280.93,0,CN,1607208884,74,121.19,1.34
54,bulawayo,-20.15,289.02,100,ZW,1607208884,93,28.58,6.01

In [58]:
locations = clean[['lat','long']]
weights = clean['humidity']
gmaps.configure(g_key)
fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(locations, weights = weights, dissipating = False, max_intensity=30,point_radius=1)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [59]:
locations = clean[['lat','long']]
weights = clean['humidity']
gmaps.configure(g_key)
fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(locations, weights = weights, dissipating = False, max_intensity=30,point_radius=1)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [60]:
#### jen fix the temps!!!

## max temp 291
## min temp 257
## wind speed < 10
##cloudiness < 25
# humidity < 50

jens_vacay = clean.loc[(clean.max_temp < 291) & (clean.max_temp > 257)
                       & (clean.cloudiness < 25)
                      & (clean.humidity < 75)
                      & (clean.wind_speed < 5)]
jens_vacay

,city,lat,max_temp,cloudiness,country,date,humidity,long,wind_speed
17,hamilton,39.18,277.59,20,US,1607208717,73,-84.53,0.45
19,anaconda,46.13,277.15,1,US,1607208866,38,-112.94,2.02
39,constitucion,-35.33,288.93,9,CL,1607208871,70,-72.42,3.91
42,victoria,22.29,289.26,0,HK,1607208503,71,114.16,0.45
53,juegang,32.32,280.93,0,CN,1607208884,74,121.19,1.34

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [61]:
hotel_df = []
jens_vacay['hotel name'] = ""
target_type = 'lodging'
radius = 5000
seattle_coords = "39.18,-84.53"

# Build URL using the Google Maps API
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

for row in jens_vacay:
    spots = list(zip(jens_vacay.lat,jens_vacay.long))
spots

[(39.18, -84.53),
 (46.13, -112.94),
 (-35.33, -72.42),
 (22.29, 114.16),
 (32.32, 121.19)]

In [67]:
#for spot in spots:    
location = "39.18,-84.53"
types = target_type
radius = 5000
key = g_key

params = {
        "location": location,
        "types": target_type,
        "radius": radius,
        "key": g_key
        }
response = requests.get(base_url, params)
jens_hotel = response.json()
print(json.dumps(jens_hotel, indent=4, sort_keys=True))

{
    "error_message": "You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started",
    "html_attributions": [],
    "results": [],
    "status": "REQUEST_DENIED"
}

In [41]:
for spot in spots:    
   # location = spots[0], spots[1]
    location = spot
location

    #response = requests.get(base_url, params).json()
    #hotel_df.append(response["results"][0]["name"])
   # https://maps.googleapis.com/maps/api/place/nearbysearch/jsonlocation={latlong}&radius=5000&type=restaurant&keyword=cruise&key=YOUR_API_KEY

#spots
#hotel_df['Hotel Name'] = []
#hotel_df

(32.32, 121.19)

In [ ]:
    params = {
        "location": location,
        "types": target_type,
        "radius": radius,
        "key": g_key
}

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure